services:
  - docker

before_install:
  - docker build -t sloppy/oh-hai:travis .
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker push sloppy/oh-hai:travis

after_success:
  - curl -L https://files.sloppy.io/sloppy-`uname -s`-`uname -m` > sloppy
  - chmod +x sloppy
  - ./sloppy show
